# This file determines which shields will be built for which boards.
# By default, only the settings_reset firmware will be built for boards that have been tested with MechWild shields. Some others have been added commented out, so you can see the format.
# Remove the boards and/or shields you don't need, and add/uncomment the ones you do need.

# USB LOGGING:
# Add `snippet: zmk-usb-logging` to the board/shield combination, e.g.
#  - board: nice_nano_v2
#    shield: murphpad
#    snippet: zmk-usb-logging

# ADVANCED:
# You can use the `cmake-args` property to pass flags to the build command, and `artifact-name` to assign a name to distinguish build outputs from each other:
#  - board: nice_nano_v2
#    shield: murphpad
#    snippet: studio-rpc-usb-uart
#    cmake-args: -DCONFIG_ZMK_STUDIO=y
#    artifact-name: murphpad_studio
---
include:
#  - board: pillbug
#    shield: bb40
#  - board: pillbug
#    shield: bb65
#  - board: pillbug
#    shield: bbpad
  - board: nice_nano_v2
    shield: bde_rev2
#  - board: nice_nano_v2
#    shield: mokulua_left
#  - board: nice_nano_v2
#    shield: mokulua_right
#  - board: nice_nano_v2
#    shield: murphpad
#  - board: pillbug
#    shield: obe
#  - board: pillbug
#    shield: waka60
#  - board: nice_nano
#    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
#  - board: pillbug@0.1
#    shield: settings_reset
#  - board: pillbug
#    shield: settings_reset
#  - board: blackpill_f401cc
#    shield: settings_reset
#  - board: blackpill_f401ce
#    shield: settings_reset
#  - board: blackpill_f411ce
#    shield: settings_reset
